# Generated by Django 5.2.5 on 2025-08-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_rename_owner_to_farmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
