# Generated by Django 5.2.4 on 2025-08-28 21:45

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_category_parent_category_slug_product_discount_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('farmer', 'slug', 'harvest_date')},
        ),
    ]
