# Generated by Django 5.2.5 on 2025-08-29 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_harvest_date_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(default=datetime.date(2025, 8, 29)),
        ),
    ]
