# Generated by Django 5.2.5 on 2025-08-29 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
